### ISSUE TITLE
related doesn't work with attrs 22.1.0

### ISSUE THREAD

**Issue by jogo** [genomoncology/related#55]
https://www.attrs.org/en/stable/changelog.html#id1 attrs 22.1.0 dropped python 2 support and now causes the following error

```
File "/usr/local/lib/python3.7/dist-packages/related/__init__.py", line 44, in <module>
   from . import dispatchers  # noqa F401
 File "/usr/local/lib/python3.7/dist-packages/related/dispatchers.py", line 8, in <module>
   from attr._compat import iteritems
ImportError: cannot import name 'iteritems' from 'attr._compat' (/usr/local/lib/python3.7/dist-packages/attr/_compat.py)
```

**Comment by imaurer** [comment]
@jogo we did get a fix in place and pushed out a new version of related. sorry for the slow reply.

https://pypi.org/project/related/0.7.3/

**Comment by jogo** [comment]
Thank you!
